/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the InboundNatRuleListResult class.
 * @constructor
 * Response for ListInboundNatRule API service call.
 *
 * @member {string} [nextLink] The URL to get the next set of results.
 *
 */
class InboundNatRuleListResult extends Array {
  constructor() {
    super();
  }

  /**
   * Defines the metadata of InboundNatRuleListResult
   *
   * @returns {object} metadata of InboundNatRuleListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'InboundNatRuleListResult',
      type: {
        name: 'Composite',
        className: 'InboundNatRuleListResult',
        modelProperties: {
          value: {
            required: false,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'InboundNatRuleElementType',
                  type: {
                    name: 'Composite',
                    className: 'InboundNatRule'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = InboundNatRuleListResult;
